"""Add Date to post

Revision ID: 1f97656ad968
Revises: 4071abfd7a77
Create Date: 2022-09-19 21:59:03.429525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f97656ad968'
down_revision = '4071abfd7a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("Update posts set created_at = '2022-09-19 21:08:49.215954' where created_at is Null;")
    op.alter_column('posts','created_at',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
