"""Add initial post and category

Revision ID: 4071abfd7a77
Revises: 
Create Date: 2022-09-04 19:06:50.491273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4071abfd7a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_category_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_category_fkey', 'posts', 'categories', ['category'], ['id'])
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###
