"""Initial migration user.

Revision ID: 4bc6a5e6088c
Revises: 
Create Date: 2022-09-04 15:02:38.351405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc6a5e6088c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disable_account', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedIn_link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('instagram_link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'github_link')
    op.drop_column('users', 'instagram_link')
    op.drop_column('users', 'linkedIn_link')
    op.drop_column('users', 'facebook_link')
    op.drop_column('users', 'disable_account')
    # ### end Alembic commands ###
